### ISSUE TITLE
Natspec

### ISSUE THREAD

**Issue by 0xzhiqi** [CaixiangFan/sol-weekly-projects#1]
https://github.com/CaixiangFan/sol-weekly-projects/blob/a1b7f17f387154a3a7fcbb68832bb83aa98a4ebd/week2/contracts/Token.sol#L9

Hi, you may want to add Natspec in the contract to help users and other developers better understand how it works

**Comment by CaixiangFan** [comment]
Resolved. Thanks.
Forgot to close it in the commit and I will put the hash here: 1e3f7b7eeadbf5d0722f0f86f4061acc9ad5c9a0
