### ISSUE TITLE
Natspec

### ISSUE THREAD

**Issue by 0xzhiqi** [CaixiangFan/sol-weekly-projects#2]
https://github.com/CaixiangFan/sol-weekly-projects/blob/a1b7f17f387154a3a7fcbb68832bb83aa98a4ebd/week2/contracts/CustomBallot.sol#L4

Hi, like in Token.sol, you may also want to add Natspec to this contract to help users and other developers better understand how it works

**Comment by CaixiangFan** [comment]
Resolved. Thank you.
